### ISSUE TITLE
Digital Signatures Broken in 10.12 - BUG

### ISSUE THREAD

**Issue by mikedvzo** [UniversalMailer/UniversalMailer#80]
Creating separate issue fore Digital Signatures.  As long as UM is installed it will break Digital Signatures in 10.12 even if it is not enabled.  

Another user has confirmed the issue as posted in previous post:
kecinzer commented 2 hours ago
Hello. I can confirm bug with digital signatures (SMIME) also. May be will be better to create own issue :).

**Comment by kecinzer** [comment]
Thanks for separete issue :).

**Comment by UniversalMailer** [comment]
Hi, could you check with the new version (3b15)? There was an issue that prevented the plugin to exclude itself when detecting S/MIME emails and it should now be solved.

As a reminder: the plugin is not working (and will not be) with tools such as GPGTools. The reason for that is because it kicks in after the email has been signed and thus breaks the signature. The problem has been discussed in the past with GPGTools authors and the solution was (and still is) to exclude the plugin when a digital signature is detected.

**Comment by mikedvzo** [comment]
Yes it is working fine again.  Thanks for the quick response and fix


-- 
Michael DiVincenzo
mdvzo@yahoo.com 


On October 06, 2016 at 10:33:39 AM, Universal Mailer (notifications@github.com) wrote:

Hi, could you check with the new version (3b15)? There was an issue that prevented the plugin to exclude itself when detecting S/MIME emails and it should now be solved.

As a reminder: the plugin is not working (and will not be) with tools such as GPGTools. The reason for that is because it kicks in after the email has been signed and thus breaks the signature. The problem has been discussed in the past with GPGTools authors and the solution was (and still is) to exclude the plugin when a digital signature is detected.

**Comment by mikedvzo** [comment]
Looks like it is broken again.  Both my machines are exhibiting the same behavior.  After you install it things work fine but then break after you restart mail and the fonts get messed up and Digital Sig comes through as SMIME.  I have points selected.  


-- 
Michael DiVincenzo
mdvzo@yahoo.com 


On October 06, 2016 at 10:33:39 AM, Universal Mailer (notifications@github.com) wrote:

Hi, could you check with the new version (3b15)? There was an issue that prevented the plugin to exclude itself when detecting S/MIME emails and it should now be solved.

As a reminder: the plugin is not working (and will not be) with tools such as GPGTools. The reason for that is because it kicks in after the email has been signed and thus breaks the signature. The problem has been discussed in the past with GPGTools authors and the solution was (and still is) to exclude the plugin when a digital signature is detected.

**Comment by mikedvzo** [comment]
Just to be clear I have "use points instead of Pixels" unselected.   I tried turning of Digital Signature in the message and now it is coming through with the correct fonts.  If I check the Digital signature box the fonts get big and the SMIME attachment appears.  See embedded messages:

  


-- 
Michael DiVincenzo
mdvzo@yahoo.com 


On October 10, 2016 at 2:32:14 PM, Michael DiVincenzo (mdvzo@yahoo.com) wrote:

Looks like it is broken again.  Both my machines are exhibiting the same behavior.  After you install it things work fine but then break after you restart mail and the fonts get messed up and Digital Sig comes through as SMIME.  I have points selected.  


-- 
Michael DiVincenzo
mdvzo@yahoo.com 


On October 06, 2016 at 10:33:39 AM, Universal Mailer (notifications@github.com) wrote:

Hi, could you check with the new version (3b15)? There was an issue that prevented the plugin to exclude itself when detecting S/MIME emails and it should now be solved.

As a reminder: the plugin is not working (and will not be) with tools such as GPGTools. The reason for that is because it kicks in after the email has been signed and thus breaks the signature. The problem has been discussed in the past with GPGTools authors and the solution was (and still is) to exclude the plugin when a digital signature is detected.

**Comment by UniversalMailer** [comment]
I have some problems understanding what's happening here. Let me know if this is what you intended:

- the plugin is working fine if no digital signature is requested (which is ok)
- the plugin is not working if the digital signature feature is turned on (which is ok)
- the plugin is not working if the digital signature feature is turned on and the signature itself is broken (which is NOT ok)

Are those points correct? Also: the points/pixels option it's not related to the digital signature feature (i.e. having it checked or unchecked will not change the behaviour described above)

**Comment by mikedvzo** [comment]
Sorry for the confusion.  Your first 2 points are correct but I am not sure I understand the third one.  

The primary problem after further troubleshooting is that if Digital Signatures are turned on then the Font size is not maintained in the message and the Digital Signature comes through as an attachment.  This was not the behavior in 10.11.  I never had an issue before to my knowledge, with the font size or Digital signature showing up as Mime.  

In addition if I disable UM I still cannot use Digital Signatures.  I need to uninstall the program if I wish to do so.  

I am also wondering what problem at this point UM is fixing since I have no issues with fonts or ATT attachments anymore in Mail.app nor do I see an issue in the messages I send if I view them in OWA or Outlook.


-- 
Michael DiVincenzo
mdvzo@yahoo.com 


On October 10, 2016 at 3:57:53 PM, Universal Mailer (notifications@github.com) wrote:

I have some problems understanding what's happening here. Let me know if this is what you intended:

the plugin is working fine if no digital signature is requested (which is ok)
the plugin is not working if the digital signature feature is turned on (which is ok)
the plugin is not working if the digital signature feature is turned on and the signature itself is broken (which is NOT ok)
Are those points correct? Also: the points/pixels option it's not related to the digital signature feature (i.e. having it checked or unchecked will not change the behaviour described above)

**Comment by mikedvzo** [comment]
It does look like the font is being maintained after I have rebooted for now but still cannot use the program if Digital Signatures are enabled.   If I don’t send a Digital Signature it is fine. I would be nice if I was to send a Digital Signature and disabled UM it would still work without having to uninstall the program.  I am pretty certain it worked in the past on 10.11.


-- 
Michael DiVincenzo
mdvzo@yahoo.com 


On October 23, 2016 at 9:24:12 PM, Michael DiVincenzo (mdvzo@yahoo.com) wrote:

Did you get this reply?

-------

Sorry for the confusion.  Your first 2 points are correct but I am not sure I understand the third one.  

The primary problem after further troubleshooting is that if Digital Signatures are turned on then the Font size is not maintained in the message and the Digital Signature comes through as an attachment.  This was not the behavior in 10.11.  I never had an issue before to my knowledge, with the font size or Digital signature showing up as Mime.  

In addition if I disable UM I still cannot use Digital Signatures.  I need to uninstall the program if I wish to do so.  

I am also wondering what problem at this point UM is fixing since I have no issues with fonts or ATT attachments anymore in Mail.app nor do I see an issue in the messages I send if I view them in OWA or Outlook.


-- 
Michael DiVincenzo
mdvzo@yahoo.com 


On October 10, 2016 at 3:57:53 PM, Universal Mailer (notifications@github.com) wrote:

I have some problems understanding what's happening here. Let me know if this is what you intended:

the plugin is working fine if no digital signature is requested (which is ok)
the plugin is not working if the digital signature feature is turned on (which is ok)
the plugin is not working if the digital signature feature is turned on and the signature itself is broken (which is NOT ok)
Are those points correct? Also: the points/pixels option it's not related to the digital signature feature (i.e. having it checked or unchecked will not change the behaviour described above)

**Comment by mikedvzo** [comment]
Did you get this reply?

-------

Sorry for the confusion.  Your first 2 points are correct but I am not sure I understand the third one.  

The primary problem after further troubleshooting is that if Digital Signatures are turned on then the Font size is not maintained in the message and the Digital Signature comes through as an attachment.  This was not the behavior in 10.11.  I never had an issue before to my knowledge, with the font size or Digital signature showing up as Mime.  

In addition if I disable UM I still cannot use Digital Signatures.  I need to uninstall the program if I wish to do so.  

I am also wondering what problem at this point UM is fixing since I have no issues with fonts or ATT attachments anymore in Mail.app nor do I see an issue in the messages I send if I view them in OWA or Outlook.


-- 
Michael DiVincenzo
mdvzo@yahoo.com 


On October 10, 2016 at 3:57:53 PM, Universal Mailer (notifications@github.com) wrote:

I have some problems understanding what's happening here. Let me know if this is what you intended:

the plugin is working fine if no digital signature is requested (which is ok)
the plugin is not working if the digital signature feature is turned on (which is ok)
the plugin is not working if the digital signature feature is turned on and the signature itself is broken (which is NOT ok)
Are those points correct? Also: the points/pixels option it's not related to the digital signature feature (i.e. having it checked or unchecked will not change the behaviour described above)

**Comment by UniversalMailer** [comment]
Sorry, I might have missed that.

Anyway: be sure to install the latest version (build 15), since I updated the code that checks and deals with digital signatures.

Also, don't expect the plugin to do anything when digital signature is turned on: it does not work. The problem is that if the plugin does its job when you digitally sign emails it will break your signature, and this is not a problem I'm addressing (and it's not something I think I'll address in a future release).

So, to be clear: if you use digital signatures the plugin will not work, it will not force a font nor solve the attachments issue.

**Comment by mikedvzo** [comment]
Correct the problem is that with the plugin installed and not enabled digital signatures break and become mime attachments

Mike DiVincenzo
mdvzo@yahoo.com
919-392-2265 (Main)
919-741-8314 (Mobile)

**Comment by mikedvzo** [comment]
Sorry to bug you but is there no way to make this work so that I can send a Digital Signature once in awhile without uninstall UM.  


-- 
Michael DiVincenzo
mdvzo@yahoo.com 


On October 23, 2016 at 9:51:24 PM, Michael DiVincenzo (mdvzo@yahoo.com) wrote:

It does look like the font is being maintained after I have rebooted for now but still cannot use the program if Digital Signatures are enabled.   If I don’t send a Digital Signature it is fine. I would be nice if I was to send a Digital Signature and disabled UM it would still work without having to uninstall the program.  I am pretty certain it worked in the past on 10.11.


-- 
Michael DiVincenzo
mdvzo@yahoo.com 


On October 23, 2016 at 9:24:12 PM, Michael DiVincenzo (mdvzo@yahoo.com) wrote:

Did you get this reply?

-------

Sorry for the confusion.  Your first 2 points are correct but I am not sure I understand the third one.  

The primary problem after further troubleshooting is that if Digital Signatures are turned on then the Font size is not maintained in the message and the Digital Signature comes through as an attachment.  This was not the behavior in 10.11.  I never had an issue before to my knowledge, with the font size or Digital signature showing up as Mime.  

In addition if I disable UM I still cannot use Digital Signatures.  I need to uninstall the program if I wish to do so.  

I am also wondering what problem at this point UM is fixing since I have no issues with fonts or ATT attachments anymore in Mail.app nor do I see an issue in the messages I send if I view them in OWA or Outlook.


-- 
Michael DiVincenzo
mdvzo@yahoo.com 


On October 10, 2016 at 3:57:53 PM, Universal Mailer (notifications@github.com) wrote:

I have some problems understanding what's happening here. Let me know if this is what you intended:

the plugin is working fine if no digital signature is requested (which is ok)
the plugin is not working if the digital signature feature is turned on (which is ok)
the plugin is not working if the digital signature feature is turned on and the signature itself is broken (which is NOT ok)
Are those points correct? Also: the points/pixels option it's not related to the digital signature feature (i.e. having it checked or unchecked will not change the behaviour described above)

**Comment by kecinzer** [comment]
I can confirm, that this bug isn't fixed.
When I submit mail with digital signature, I get "smime.p7s" attachement.

**Comment by mikedvzo** [comment]
Thx


-- 
Michael DiVincenzo
mdvzo@yahoo.com 


On November 01, 2016 at 2:48:39 PM, Petr Řezníček (notifications@github.com) wrote:

I can confirm, that this bug isn't fixed.
When I submit mail with digital signature, I get "smime.p7s" attachement.

**Comment by andreaskasa** [comment]
I can confirm this bug. Only deinstall UniversalMailer fixed it for me.

**Comment by SebStar** [comment]
This bug is so terrible :-(
UM makes SMIME completely unusable.
Signatures are always attached. I Cant read encrypted Mails on the iPhone when they are sent from a client which has UM enabled.

**Comment by UniversalMailer** [comment]
With the latest release (v3b16) I included a new way of detecting S/MIME which I cannot test since I don't have a valid certificate for my email account. If anyone is able to test and confirm it the patch is working it would be of help.

**Comment by andreaskasa** [comment]
A first test with GPGMail 2.7b3 was positive with signed and encrypted. thx

**Comment by SebStar** [comment]
Works flawless.. Messages are visible on our iPhones, the strange first line in Apple Mail (--daa8E9Eca2892....) has disappeared an Apple Mail now marks the E-Mail as encrypted.
You saved my ass.. thank you so much!
A little donation is on the way...

**Comment by UniversalMailer** [comment]
That's a very good news! I'm keeping this thread open for some time, if you notice something unexpected drop me a line here or by email.

**Comment by mikedvzo** [comment]
I just tested this on my Exchange Account by sending my self a message and  the message is not being received Digitally signed.   It contains an smime.p7s attachment instead.  I verified that if I remove UM and send a signed message it works fine.  

Anyone else test this with an Exchange account?

**Comment by SebStar** [comment]
Same here but for me this is not a big deal since encrypted mails now working fine... this was a way bigger issue.
But i can confirm signed messages still containing the smime.p7s attachment. 
Tested via IMAP and Exchange.

**Comment by mikedvzo** [comment]
Just wanted to give you heads up that I got an error when loading Mail 11.0 on Mac OS 10.13 so I modified the values in the Universal Mailer Info.plist and I am testing with 10.13.


-- 
Mike

On October 26, 2016 at 12:48:06 PM, Michael DiVincenzo (mdvzo@yahoo.com) wrote:

Correct the problem is that with the plugin installed and not enabled digital signatures break and become mime attachments

Mike DiVincenzo
mdvzo@yahoo.com
919-392-2265 (Main)
919-741-8314 (Mobile)

On Oct 26, 2016, at 1:29 AM, Universal Mailer <notifications@github.com> wrote:

Sorry, I might have missed that.

Anyway: be sure to install the latest version (build 15), since I updated the code that checks and deals with digital signatures.

Also, don't expect the plugin to do anything when digital signature is turned on: it does not work. The problem is that if the plugin does its job when you digitally sign emails it will break your signature, and this is not a problem I'm addressing (and it's not something I think I'll address in a future release).

So, to be clear: if you use digital signatures the plugin will not work, it will not force a font nor solve the attachments issue.

**Comment by Tekkle** [comment]
Same here with OSX 10.12.6, Mail 10.3 and UM 3b19. This ist really annoying, because I have two other machines (OSX 10.10.1, Mail 8.1, UM 2.1.5 and OSX 10.10.5, Mail 8.2, UM 2.1.6) and everything is working well on them. Would appreciate it very much, if there will be a solution for later versions in future. - BTW: Are there any alternatives to format the font-face in Mail to be "Outlook compatible"?

**Comment by mikedvzo** [comment]
I still use the program and realize it will not work with Digital Signatures and I am ok with it since I barely use Digital Signatures but wish I would uncheck the "Enable Universal Mailer" checkbox and send a Digital Signature with out having to uninstall each time.

**Comment by belchfireid** [comment]
Could there be an automatic way to disable UM when the message is signed or encrypted? To turn UM off requires restarting Mail, so for now, I use a separate mail client for signed messages, which is a pain.
